GET {{apiUrl}}/repos/juliannemarik/git-analytic/contributors
Authorization: juliannemarik:{{GITHUB_OAUTH_TOKEN}}

GET /repos/:owner/:repo/commits
GET /repos/:owner/:repo/pulls
GET /repos/:owner/:repo/stats/contributors
